module
public import Sites

/-!
# The example site

Everything below is ordinary Lean. The route type is an enumeration, so the compiler checks
every internal link; the route table's completeness and URL distinctness are proven by
`decide`; the Markdown page's links are checked at compile time by `Markdown.md`.
-/

namespace Example

open Sites Sites.Html

@[expose] public section

/-- The routes. Adding one here and forgetting a page or a path is a compile error. -/
inductive Route where
  | home
  | about
  | blog
  | blogHello
  | blogDsl
  deriving DecidableEq, Repr

/-- All routes, in navigation order. -/
def routes : List Route := [.home, .about, .blog, .blogHello, .blogDsl]

/-- Where each route lives. -/
def path : Route → Path
  | .home => []
  | .about => [seg "about"]
  | .blog => [seg "blog"]
  | .blogHello => [seg "blog", seg "hello-world"]
  | .blogDsl => [seg "blog", seg "typed-html"]

/-- Route lookup, shared with the Markdown link checker. -/
def route? : List Char → Option Route := routeOfChars routes path

/-- Markdown with compile-time link checking against this site's routes. Write the content
as `chars!"..."` so the kernel gets a character list. -/
abbrev md (cs : List Char)
    (h : (Markdown.parseChars cs).linksOk route? = true := by decide +kernel) :
    List (Node Route .flow) :=
  Markdown.md route? cs h

/-- The stylesheet, in the typed CSS DSL. -/
def stylesheet : Css.Stylesheet :=
  open Css in
  [ rule .universal [.boxSizing .borderBox],
    rule .html [.fontFamily [.systemUi, .sansSerif], .lineHeight (.tenths 16),
      .color (.hex 0x1f 0x23 0x28), .backgroundColor (.hex 0xff 0xff 0xff)],
    rule .body [.margin .zero, .display .flex, .flexDirection .column,
      .minHeight (.vh 100)],
    rule (.cls "site-header") [.padding (.rem 1), .borderSide .bottom (.px 1) .solid (.hex 0xdd 0xdd 0xdd)],
    rule (.desc (.cls "site-header") (.ofTag .ul))
      [.listStyle .none, .display .flex, .gap (.rem 1), .margin .zero, .padding .zero],
    rule (.desc (.cls "site-header") (.ofTag .a)) [.textDecoration .none, .fontWeight .w600],
    rule (.cls "site-main") [.maxWidth (.rem 42), .width (.pct 100), .margin (.auto),
      .padding (.rem 1)],
    rule (.cls "site-footer") [.padding (.rem 1), .textAlign .center, .fontSize (.rem (.tenths 9)),
      .color (.hex 0x66 0x66 0x66)],
    rule (.tag .a) [.color (.hex 0x0b 0x57 0xd0)],
    rule (Selector.tag .a).hover [.textDecoration .underline],
    rule (.tag .pre) [.padding (.rem 1), .backgroundColor (.hex 0xf4 0xf4 0xf4), .overflowX .auto,
      .borderRadius (.px 4)],
    rule (.tag .code) [.fontFamily [.monospace], .fontSize (.em (.hundredths 95))],
    rule (.tag .blockquote) [.marginSide .left .zero, .paddingSide .left (.rem 1),
      .borderSide .left (.px 3) .solid (.hex 0xcc 0xcc 0xcc), .color (.hex 0x55 0x55 0x55)],
    .mediaMaxWidth (.px 600)
      [ rule (.cls "site-main") [.padding (.rem (.tenths 5))] ],
    .mediaDark
      [ rule .html [.color (.hex 0xe6 0xe6 0xe6), .backgroundColor (.hex 0x12 0x14 0x17)],
        rule (.tag .a) [.color (.hex 0x8a 0xb4 0xf8)],
        rule (.tag .pre) [.backgroundColor (.hex 0x1e 0x22 0x27)] ] ]

/-- Home page, written directly in the HTML DSL. -/
def home : Page Route :=
  { title := "Dependent Website Theory"
    description := "A static site generator written and verified in Lean 4."
    body :=
      [ p [] [ "A static site generator written in Lean 4, with its printer, its stylesheet and ",
               "its build pipeline verified. This page is a Lean term of type ",
               code [] ["Page Route"], "." ],
        h2 [] ["What is checked"],
        ul []
          [ li [] [ "Every internal link is a value of the route type: ",
                    a [.href (.route .about)] ["this link"], " cannot dangle." ],
            li [] [ "The HTML printer has a parser proven to invert it, so every file the build ",
                    "writes parses back to its document tree." ],
            li [] [ "The stylesheet is typed and its output is proven grammatical." ],
            li [] [ "The build loop carries a Hoare-triple contract proven with ", code [] ["vcgen"],
                    "." ] ],
        p [] [ "Read more on the ", a [.href (.route .blog)] ["blog"], "." ] ] }

/-- About page: Markdown, checked at compile time. -/
def about : Page Route :=
  { title := "About"
    body := md chars!"
This site is generated by `sites`, a small static site generator written in Lean 4
with none of Lean's escape hatches: every function is total, every proof is complete, and
the README lists what is proven.

## Why

Most generators promise that their output is well-formed. This one proves it. The
[home page](/) lists what is verified; the [blog](/blog/) explains how.

## Links are checked

The link to the [first post](/blog/hello-world/) is checked when this file is
compiled: change the path to a route that does not exist and the build fails.

> Markdown is parsed by a total, fuel-bounded parser that reduces inside the kernel,
> which is what makes the check a `decide` proof rather than a runtime error.
" }

/-- Blog index. -/
def blog : Page Route :=
  { title := "Blog"
    body :=
      [ p [] ["Posts:"],
        ul []
          [ li [] [a [.href (.route .blogHello)] ["Hello, world"]],
            li [] [a [.href (.route .blogDsl)] ["Typed HTML"]] ] ] }

/-- First post, Markdown. -/
def blogHello : Page Route :=
  { title := "Hello, world"
    body := md chars!"
A first post, in Markdown.

- Headings, paragraphs and lists work.
- So do **strong**, *emphasis* and `code`.
- Fenced code blocks too:

```lean
theorem parseDocument_render : parseDocument route? (d.render url) = some d
```

1. Numbered lists.
2. Are numbered.

Back to the [index](/blog/).
" }

/-- Second post, mixing the DSL and Markdown. -/
def blogDsl : Page Route :=
  { title := "Typed HTML"
    body :=
      md chars!"
The HTML tree is an inductive family indexed by content category. A `li` can only appear
inside a list, a `p` can only contain phrasing content, and text can only appear where
text is allowed.
" ++
      [ p [] [ "This paragraph is a DSL term following the Markdown above: ",
               em [] ["mixing"], " is fine because both are just ", code [] ["Node Route .flow"],
               "." ],
        blockquote [] [p [] ["Ill-nested markup is a type error, not a warning."]] ] }

/-- The site. -/
def site : Site Route :=
  { name := "Dependent Website Theory"
    routes
    routes_complete := by intro r; cases r <;> decide
    path
    urls_nodup := by decide
    page := fun
      | .home => home
      | .about => about
      | .blog => blog
      | .blogHello => blogHello
      | .blogDsl => blogDsl
    nav := [(.home, "Home"), (.about, "About"), (.blog, "Blog")]
    stylesheet }

end

end Example
